#ifndef PARAMS_H
#define PARAMS_H

#define DILITHIUM_N 256
#define DILITHIUM_Q 8380417
#define DILITHIUM_D 13

#define DILITHIUM_K 6
#define DILITHIUM_L 5
#define DILITHIUM_ETA 4
#define DILITHIUM_TAU 49
#define DILITHIUM_BETA 196
#define DILITHIUM_GAMMA1 (1 << 19)
#define DILITHIUM_GAMMA2 ((DILITHIUM_Q - 1) / 32)
#define DILITHIUM_OMEGA 75

#define SEEDBYTES 32
#define CRHBYTES 64

#define POLYT1_PACKEDBYTES 320
#define POLYT0_PACKEDBYTES 416
#define POLYVECH_PACKEDBYTES (DILITHIUM_OMEGA + DILITHIUM_K)

#define PUBLICKEYBYTES (SEEDBYTES + DILITHIUM_K * POLYT1_PACKEDBYTES)
#define PRIVATEKEYBYTES (SEEDBYTES + SEEDBYTES + CRHBYTES + DILITHIUM_L * 128 + DILITHIUM_K * 128 + DILITHIUM_K * POLYT0_PACKEDBYTES)
#define SIGNATUREBYTES (SEEDBYTES + DILITHIUM_L * 640 + POLYVECH_PACKEDBYTES)

#endif
